### ISSUE TITLE
Default region no longer supported by Tunigo API

### ISSUE THREAD

**Issue by jodal** [trygveaa/python-tunigo#2]
Quoting @trygveaa in mopidy/mopidy-spotify#42:

> It seems that the tunigo api doesn't support region=all anymore. which is what python-tunigo defaults to if region is not set. I'll fix it, and release a new version.

**Comment by trygveaa** [comment]
So it started working again with region=all, and then I forgot about this. However, seems like new releases still doesn't work with region=all. I fixed it now, so it doesn't send in any region, instead of region=all.
